services:
#server
  webserver:
    image: nginx:latest
    container_name: website-nginx
    ports:
    - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

#php
  php:
    image: php8.3:v1
    container_name: website-php
    volumes:
      - ./php/public:/var/www/html/public

#mysql
  db:
    image: mysql:8.4.3
    container_name: website-mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: g0kjVW2S7X62ozo2SjIx
      MYSQL_DATABASE: app-database
      MYSQL_USER: user-app-database
      MYSQL_PASSWORD: 5WKuCc4eHNGr3U2deer2

